// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2woxEDms158VXl6EOMGG_0roewxkZ1Ao',
    appId: '1:41177098282:web:942ef7855af6c02bc87b53',
    messagingSenderId: '41177098282',
    projectId: 'eatonomy-food-app',
    authDomain: 'eatonomy-food-app.firebaseapp.com',
    storageBucket: 'eatonomy-food-app.appspot.com',
    measurementId: 'G-WL7SYD9H3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdtgPwwKkFOfDSAmJ8-ffxg2pH_ecICOU',
    appId: '1:41177098282:android:626be36365450b45c87b53',
    messagingSenderId: '41177098282',
    projectId: 'eatonomy-food-app',
    storageBucket: 'eatonomy-food-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GghnjeKNGjVawYtsqwjZL3IOAJ7gylA',
    appId: '1:41177098282:ios:58f7f0f913addee2c87b53',
    messagingSenderId: '41177098282',
    projectId: 'eatonomy-food-app',
    storageBucket: 'eatonomy-food-app.appspot.com',
    iosBundleId: 'com.example.eatonomyFoodRecommenderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1GghnjeKNGjVawYtsqwjZL3IOAJ7gylA',
    appId: '1:41177098282:ios:75a6a47a00bf7fb9c87b53',
    messagingSenderId: '41177098282',
    projectId: 'eatonomy-food-app',
    storageBucket: 'eatonomy-food-app.appspot.com',
    iosBundleId: 'com.example.eatonomyFoodRecommenderApp.RunnerTests',
  );
}
